# Reg model

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Movie_r.csv', header = 0)
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

pre-process

In [4]:
# missing values 
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)
# dummies 
df = pd.get_dummies(df, columns=['3D_available', 'Genre'], drop_first=True)
# split 
X = df.loc[:, df.columns!='Collection']
y = df['Collection']

splitting

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

standardise

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
sc = StandardScaler().fit(X_train)

In [8]:
X_train_std = sc.transform(X_train)

In [9]:
X_test_std = sc.transform(X_test)

In [13]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

make model

In [14]:
from sklearn.svm import SVR
svr = SVR(kernel='linear', C=1000)

In [15]:
svr.fit(X_train_std, y_train)

SVR(C=1000, kernel='linear')

In [16]:
y_test_pred = svr.predict(X_test_std)
y_train_pred = svr.predict(X_train_std)

performance

In [17]:
from sklearn.metrics import mean_squared_error, r2_score

In [18]:
mean_squared_error(y_test, y_test_pred)

160153135.39404392

In [16]:
r2_score(y_train, y_train_pred)

0.7124450931551838

In [17]:
r2_score(y_test, y_test_pred)

0.5025135728682723

# classification SVM

## 1.Linear kernel

In [18]:
df = pd.read_csv('Movie_c.csv', header = 0)
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [19]:
# missing values 
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)
# dummies 
df = pd.get_dummies(df, columns=['3D_available', 'Genre'], drop_first=True)
# split 
X = df.loc[:, df.columns!='Start_Tech_Oscar']
y = df['Start_Tech_Oscar']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

standardise

In [21]:
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

model

In [22]:
from sklearn.svm import SVC

In [23]:
clf_svc = SVC(kernel='linear', C=0.01)
clf_svc.fit(X_train_std, y_train)

SVC(C=0.01, kernel='linear')

In [24]:
y_train_pred = clf_svc.predict(X_train_std)
y_test_pred = clf_svc.predict(X_test_sc)

performance

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [26]:
confusion_matrix(y_train, y_train_pred)

array([[ 33, 153],
       [  6, 212]], dtype=int64)

In [27]:
accuracy_score(y_test, y_test_pred)

0.6274509803921569

In [28]:
accuracy_score(y_train, y_train_pred)

0.6064356435643564

In [30]:
clf_svc.n_support_

array([186, 189])

## Hyper param tuning

In [29]:
from sklearn.model_selection import GridSearchCV

## diff C and diff Kernels

In [31]:
params = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000], 'kernel': ['linear', 'rbf', 'poly']}

In [34]:
clf_svc_grid = GridSearchCV(clf_svc,params, n_jobs=-1, verbose = 1,  cv=5)

In [35]:
clf_svc_grid.fit(X_train_std, y_train)

Fitting 5 folds for each of 21 candidates, totalling 105 fits


GridSearchCV(cv=5, estimator=SVC(C=0.01, kernel='linear'), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=1)

In [36]:
clf_svc_grid.best_params_

{'C': 0.1, 'kernel': 'linear'}

In [37]:
clf_svc_best = clf_svc_grid.best_estimator_

In [38]:
accuracy_score(y_test, clf_svc_best.predict(X_test_sc))

0.5980392156862745

## 2.Poly kernel

In [40]:
clf_svc2 = SVC(kernel='poly', C=0.01, degree=2)

In [41]:
clf_svc2.fit(X_train_std, y_train)
accuracy_score(y_test, clf_svc2.predict(X_test_sc))

0.5686274509803921

## 3.Radial kernel

In [42]:
clf_svc3 = SVC(kernel='rbf', C=0.01, gamma=0.1)

In [43]:
clf_svc3.fit(X_train_std, y_train)
accuracy_score(y_test, clf_svc3.predict(X_test_sc))

0.5686274509803921